service: simple-project-alert-notification

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 1024
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-2
  lambdaHashingVersion: 20201221

functions: 
  get-generated-dog-name:
    handler: src/handlers/get-generated-dog-name/endpoint.handler
    events: 
      - http: 
          path: generate/{breed}/name
          method: get
          cors: true

resources: 
  Resources: